export const FETCH_BASE_INFO = 'FETCH_BASE_INFO';
export const FETCH_NOTICE_INFO = 'FETCH_NOTICE_INFO';
export const FETCH_INIT_PWD = 'FETCH_INIT_PWD';

export const UPDATE_BASE_INFO = 'UPDATE_BASE_INFO';
export const SET_SIDE_BAR_STATE = 'SET_SIDE_BAR_STATE';